name: Build
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install --immutable --immutable-cache
      - run: yarn prettier --check .
      - run: yarn lint
  ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install --immutable --immutable-cache
      - run: yarn ts
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: ./.github/actions/setup-playwright
      - name: Run end-to-end tests
        run: yarn workspace @melodies/e2e test --project=e2e
  deploy:
    needs: [lint, ts, e2e]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: melodies-web
          heroku_email: mdskelton99@gmail.com
  verify-deployment:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: ./.github/actions/setup-playwright
      - name: Verify deployment
        run: yarn workspace @melodies/e2e test --project=smoke
